project:
  type: website
website:
  title: "kasia.codes"
  favicon: assets/images/icon.svg
  navbar:
    logo: assets/images/logo.png
    left:
      - text: Blog
        icon: pen-fill
        href: blog.qmd
      - text: Teaching
        icon: laptop-fill
        href: talks
      - text: Photography
        icon: camera-fill
        href: photography.qmd
      - text: Resume
        icon: person-fill
        href: assets/cv/resume.html
        target: "_blank"
  
      
  page-footer:
    center: 
      - text: "© 2024 Kasia Kedzierska // Made with R and Quarto"
        icon: heart-fill
        href: https://quarto.org

page-footer:
    background: black
    right: test
    left: test2

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
  