project:
  type: website
  preview: 
    port: 4321
    browser: true

execute:
  freeze: auto
website:
  title: "kasia.codes"
  repo-url: https://github.com/kzkedzierska/personal_website
  repo-actions: [source, issue]
  favicon: assets/images/icon.svg
  navbar:
    pinned: true
    logo: assets/images/logo.png
    left:
      - text: Posts
        icon: pen-fill
        href: posts
      - text: Teaching
        icon: laptop-fill
        href: talk
      - text: Photography
        icon: camera-fill
        href: photography.qmd
      - text: Resume
        icon: person-fill
        href: assets/cv/resume.html
        target: "_blank"
  
      
  page-footer:
    center: "© 2024 Kasia Kedzierska // made with ︎❤  R & [Quarto](https://quarto.org)"


format:
  html:
    theme: [sandstone, assets/custom_theme.scss]
    toc: true
    pagetitle: "Kasia Kedzierska | {{< meta title >}}"
    highlight-style: nord
    page-layout: article
    code-link: true
    smooth-scroll: true
    link-external-newwindow: true

  