on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
        
      # Cache Quarto installation
      - name: Cache Quarto
        uses: actions/cache@v3
        with:
          path: ~/.local/share/quarto
          key: ${{ runner.os }}-quarto-1.5.56
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 1.5.56
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true # Use binary packages when possible
      
      # Enhanced R package caching
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1.0.0
          
      # Cache the _site directory where Quarto renders
      - name: Cache rendered outputs
        uses: actions/cache@v3
        with:
          path: _site
          key: ${{ runner.os }}-rendered-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rendered-
      
      # Optional: If your site has large dependencies that don't change often
      - name: Cache node modules if present
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
        if: hashFiles('**/package-lock.json', '**/yarn.lock') != ''
      
      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}